import ReversibleSampling

/-! Kernel-checked dependency audit; these should use only Lean's standard logical axioms. -/

#print axioms ReversibleSampling.complete_markov
#print axioms ReversibleSampling.complete_reversible
#print axioms ReversibleSampling.complete_invariant
#print axioms ReversibleSampling.accept_reject_correct
#print axioms ReversibleSampling.mass_mul_mh
#print axioms ReversibleSampling.mh_accepted_flow_symmetric
#print axioms ReversibleSampling.metropolis_hastings_correct
#print axioms ReversibleSampling.deterministic_accepted_flow_density
#print axioms ReversibleSampling.involution_accepted_flow_symmetric
#print axioms ReversibleSampling.involution_metropolis_correct
#print axioms ReversibleSampling.invariant_preserves_physical_marginal
#print axioms ReversibleSampling.product_auxiliary_marginal
#print axioms ReversibleSampling.conditional_auxiliary_marginal
#print axioms ReversibleSampling.conditional_auxiliary_update_preserves_marginal
#print axioms ReversibleSampling.invariant_hybrid
#print axioms ReversibleSampling.importance_sampling_lintegral
#print axioms ReversibleSampling.normalized_importance_sampling
#print axioms ReversibleSampling.unbiased_auxiliary_weight_marginal
#print axioms ReversibleSampling.randomized_importance_sampling
#print axioms ReversibleSampling.poisson_pgf_hasSum
#print axioms ReversibleSampling.poisson_pgf_lintegral
#print axioms ReversibleSampling.poisson_depletion_mean
#print axioms ReversibleSampling.poisson_depletion_second_moment
#print axioms ReversibleSampling.poisson_depletion_relative_variance
#print axioms ReversibleSampling.poisson_auxiliary_weight_marginal
#print axioms ReversibleSampling.poisson_importance_sampling
#print axioms ReversibleSampling.countGate_pointwise_balance
#print axioms ReversibleSampling.countGate_accepted_flow_symmetric
#print axioms ReversibleSampling.countGate_metropolis_correct
#print axioms ReversibleSampling.poissonCountMass_normalized
#print axioms ReversibleSampling.poisson_depletion_count_flow
#print axioms ReversibleSampling.poisson_depletion_count_factor
#print axioms ReversibleSampling.poisson_gate_term_correction
#print axioms ReversibleSampling.conditional_poisson_metropolis_correct
#print axioms ReversibleSampling.poissonGateAcceptance_zero_activity
#print axioms ReversibleSampling.poissonCountMass_zero_changes
#print axioms ReversibleSampling.poissonGateAcceptance_zero_changes
#print axioms ReversibleSampling.conditional_poisson_zero_activity_correct
